import os

Import('env')
with open(env['PROJECT_TOOL_S']) as f:
    exec(f.read())


SRCS = append_srcs_dir(ADir('src'))
INCLUDE = [ADir('include'), ADir('.')]
PRIVATE_INCLUDE = [ADir('../include')]
REQUIREMENTS = ['pthread','atomic','rt', 'dl', 'm', 'ax_msp', 'utilities', 'eventpp', 'StackFlow']
STATIC_LIB = []
DYNAMIC_LIB = []
DEFINITIONS = []
DEFINITIONS_PRIVATE = []
LDFLAGS = []
LINK_SEARCH_PATH = []
STATIC_FILES = []

# REQUIREMENTS += ['Backward_cpp']
# DYNAMIC_LIB += [ AFile('../static_lib/libdw.so.1'),
#                 AFile('../static_lib/libelf.so.1'),
#                 AFile('../static_lib/libz.so.1'),
#                 AFile('../static_lib/liblzma.so.5'),
#                 AFile('../static_lib/libbz2.so.1.0')]
# DEFINITIONS += ["-DENABLE_BACKWARD"]
DEFINITIONS += ['-O2']
DEFINITIONS += ['-std=c++17']
LDFLAGS+=['-Wl,-rpath=/opt/m5stack/lib', '-Wl,-rpath=/usr/local/m5stack/lib', '-Wl,-rpath=/usr/local/m5stack/lib/gcc-10.3', '-Wl,-rpath=/opt/lib', '-Wl,-rpath=/opt/usr/lib', '-Wl,-rpath=./']
REQUIREMENTS += ['ax_engine', 'ax_interpreter', 'ax_sys', 'utilities']
LINK_SEARCH_PATH += [ADir('../static_lib')]


INCLUDE += [ADir('src/runner'), ADir('src/runner/utils')]
INCLUDE += [ADir('../include/sentencepiece'),
            ADir('../include/protobuf-lite'),
            ADir('../include/abseil-cpp'),
            ADir('../include/re2')]

static_file = Glob('../static_lib/module-llm/libabsl_*')
static_file += [AFile('../static_lib/module-llm/libre2.a'), AFile('../static_lib/module-llm/libsentencepiece.a'), AFile('../static_lib/module-llm/libsentencepiece_train.a')]
STATIC_LIB += static_file * 4

STATIC_FILES += Glob('scripts/tokenizer_*.py')
STATIC_FILES += Glob('models/mode_*.json')
STATIC_FILES += [AFile('scripts/llm-llm_tokenizer_auto.py')]

env['COMPONENTS'].append({'target':'llm_llm',
                          'SRCS':SRCS,
                          'INCLUDE':INCLUDE,
                          'PRIVATE_INCLUDE':PRIVATE_INCLUDE,
                          'REQUIREMENTS':REQUIREMENTS,
                          'STATIC_LIB':STATIC_LIB,
                          'DYNAMIC_LIB':DYNAMIC_LIB,
                          'DEFINITIONS':DEFINITIONS,
                          'DEFINITIONS_PRIVATE':DEFINITIONS_PRIVATE,
                          'LDFLAGS':LDFLAGS,
                          'LINK_SEARCH_PATH':LINK_SEARCH_PATH,
                          'STATIC_FILES':STATIC_FILES,
                          'REGISTER':'project'
                          })

